apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\windows\system32\Kompose.exe convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: ingestion-service
  name: ingestion-service
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: ingestion-service
