apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\windows\system32\Kompose.exe convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: storage-service
  name: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\windows\system32\Kompose.exe convert --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: storage-service
    spec:
      containers:
        - image: ayoubmk02/storage-service
          name: storage-service
      restartPolicy: Always
